version: "3.8"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring
    networks:
      - springboot-mysql-net
 
  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    image: spring-image
    ports:
      - "9016:9016"
    depends_on:
      - mysqldb
    networks:
      - springboot-mysql-net
    restart: on-failure
networks:
  springboot-mysql-net: